### ISSUE TITLE
Images missing max-width property

### ISSUE THREAD

**Issue by paskal** [fiatjaf/classless-hugo#1]
Hello!

Thanks for a very nice theme! I've stumbled upon the very same issue as the https://github.com/dim0627/hugo_theme_beg/issues/19, only part of the image visible on the screenshot where whole should be. Source code:

    ![Shinken simple distributed architecture](https://shinken.readthedocs.io/en/latest/_images/shinken-architecture.png)

Only several sub-themes affected:

jeen:
![image](https://user-images.githubusercontent.com/712534/38767721-88afd9e8-3fef-11e8-8654-65fa8fabc388.png)
freelancer:
![image](https://user-images.githubusercontent.com/712534/38767725-9c50a856-3fef-11e8-8336-814cccd3f82c.png)
aloud:
![image](https://user-images.githubusercontent.com/712534/38767735-bc2c09c2-3fef-11e8-8e76-434f8ca48c3b.png)

**Comment by fiatjaf** [comment]
I'm slowly improving themes. I haven't touched the ones you mentioned for a long time now, that's why they have a lot of weak points. I've quickly fixed the `max-width` for images in them on https://github.com/fiatjaf/classless/commit/12e451501c324b89363765b65d913e050a5c3bf6, but they still need more love.
